package com.example.ybmt.jun.orm.mbg.mapper.sample;

import com.example.ybmt.jun.orm.mbg.model.sample.UserDetails;
import com.example.ybmt.jun.orm.mbg.model.sample.UserDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.user_details
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    @SelectProvider(type=UserDetailsSqlProvider.class, method="countByExample")
    long countByExample(UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.user_details
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    @DeleteProvider(type=UserDetailsSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.user_details
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    @Insert({
        "insert into sample.user_details (user_id, email, ",
        "address)",
        "values (#{userId,jdbcType=INTEGER}, #{email,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR})"
    })
    int insert(UserDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.user_details
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    @InsertProvider(type=UserDetailsSqlProvider.class, method="insertSelective")
    int insertSelective(UserDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.user_details
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    @SelectProvider(type=UserDetailsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR)
    })
    List<UserDetails> selectByExample(UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.user_details
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    @UpdateProvider(type=UserDetailsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserDetails record, @Param("example") UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.user_details
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    @UpdateProvider(type=UserDetailsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserDetails record, @Param("example") UserDetailsExample example);
}