package com.example.ybmt.jun.orm.mbg.model.sample;

public class UserDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.user_details.user_id
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.user_details.email
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.user_details.address
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.user_details.user_id
     *
     * @return the value of sample.user_details.user_id
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.user_details.user_id
     *
     * @param userId the value for sample.user_details.user_id
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.user_details.email
     *
     * @return the value of sample.user_details.email
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.user_details.email
     *
     * @param email the value for sample.user_details.email
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.user_details.address
     *
     * @return the value of sample.user_details.address
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.user_details.address
     *
     * @param address the value for sample.user_details.address
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}