package com.example.ybmt.jun.orm.mbg.model.sample;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.users.user_id
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.users.status
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.users.name
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.users.password
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.users.user_id
     *
     * @return the value of sample.users.user_id
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.users.user_id
     *
     * @param userId the value for sample.users.user_id
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.users.status
     *
     * @return the value of sample.users.status
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.users.status
     *
     * @param status the value for sample.users.status
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.users.name
     *
     * @return the value of sample.users.name
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.users.name
     *
     * @param name the value for sample.users.name
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.users.password
     *
     * @return the value of sample.users.password
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.users.password
     *
     * @param password the value for sample.users.password
     *
     * @mbg.generated Wed Aug 18 14:54:40 JST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}